[package]
name = "hosting"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
description = """
Includes the code-generated implementation of the hosting
api.
"""
edition = "2018"

[dependencies]
base64 = "0.9"
failure = "0.1"
futures = "0.1"
hyper = "0.12"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
serde_yaml = "0.7"
typed-headers = "0.1"
url = "1.5"

edgelet-core = { path = "../edgelet-core" }
