build_id: 42
test_duration:
  secs: 28800 # 8 hours
  nanos: 0
alert:
  scheme: http
  host: localhost
  path: /workflows/id/triggers/manual/paths/invoke
  query:
    api-version: 2016-10-01
    sp: /triggers/manual/run
    sv: 1.0
    sig: password
  url: http://localhost/workflows/id/triggers/manual/paths/invoke?api-version=2016-10-01&sp=%2Ftriggers%2Fmanual%2Frun&sv=1.0&sig=password
analyzer_url: http://analyzer:15000/api/report
blob_storage_account: ''
blob_storage_master_key: ''
reporting_interval: null
management_uri: unix:///var/lib/iotedge/mgmt.sock
