[package]
authors = ["Azure IoT Edge Devs"]
description = "A json-based authorization policy engine."
edition = "2018"
name = "policy"
version = "0.1.0"

[dependencies]
lazy_static = "1"
proptest = { version = "0.10", optional = true }
regex = "1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"

[dev-dependencies]
matches = "0.1"
itertools = "0.10"
