[package]
name = "mqttd"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2018"

[dependencies]
atty = "0.2"
failure = "0.1"
futures-util = { version = "0.3", features = ["sink"] }
tokio = { version = "0.2", features = ["dns", "rt-threaded", "signal", "stream", "tcp", "time"] }
tracing = "0.1"
tracing-subscriber = "0.1"

mqtt-broker = { path = "../mqtt-broker" }

