[package]
name = "edgelet-utils"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
edition = "2018"

[dependencies]
failure = "0.1.2"
log = "0.4"
serde = "1.0"
serde_json = "1.0"

[dev_dependencies]
futures = "0.1"
serde_derive = "1.0"
