[package]
name = "edgelet-utils"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
edition = "2021"

[dependencies]
config = { version = "0.11", default-features = false }
log = "0.4"
serde = "1.0"
serde_json = "1.0"
thiserror = "1"
yaml-rust = "0.4"

[dev_dependencies]
tokio = { version = "1", features = ["rt", "macros"]}
serde_derive = "1.0"
