[package]
name = "provisioning"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
edition = "2018"

[dependencies]
base64 = "0.9"
bytes = "0.4"
failure = "0.1"
futures = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
url = "1.7"
sha2 = "0.7.0"

hsm = { path = "../hsm-rs"}
dps = { path = "../dps" }
edgelet-core = { path = "../edgelet-core" }
edgelet-hsm = { path = "../edgelet-hsm" }
edgelet-http = { path = "../edgelet-http" }
edgelet-http-external-provisioning = { path = "../edgelet-http-external-provisioning" }
edgelet-utils = { path = "../edgelet-utils" }
external-provisioning = { path = "../external-provisioning" }

[dev_dependencies]
tempdir = "0.3.7"
tokio = "0.1.8"

edgelet-config = { path = "../edgelet-config" }
