[build.env]
passthrough = [
    "BUILD_SOURCEVERSION",
    "VERSION",
    "IOTEDGE_HOMEDIR",
]

[target.x86_64-unknown-linux-gnu]
image = "azureiotedge/debian-build:9.5-1"

[target.armv7-unknown-linux-gnueabihf]
image = "azureiotedge/gcc-linaro-7.3.1-2018.05-x86_64_arm-linux-gnueabihf:debian_9.5-1"

[target.aarch64-unknown-linux-gnu]
image = "azureiotedge/gcc-linaro-7.3.1-2018.05-x86_64_aarch64-linux-gnu:debian_9.5-1"

[target.armv7-unknown-linux-musleabihf]
# Built from rust-embedded/cross#718a19cd68fb09428532d1317515fe7303692b47 with `./build-docker-image.sh armv7-unknown-linux-musleabihf`
# because the image in Docker hub is outdated and broken
image = "azureiotedge/armv7-unknown-linux-musleabihf:0.1"

[target.aarch64-unknown-linux-musl]
# Built from rust-embedded/cross#718a19cd68fb09428532d1317515fe7303692b47 with `./build-docker-image.sh aarch64-unknown-linux-musl`
# because the image in Docker hub is outdated and broken
image = "azureiotedge/aarch64-unknown-linux-musl:0.1"