[package]
name = "prep-mail"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false

[dependencies]
env_logger = "0.5"
futures = "0.1"
handlebars = "1.0"
hyper = "0.12"
hyper-tls = "0.3.0"
serde = "1.0"
serde_json = "1.0"
tokio = "0.1"
url = "1.7"

snitcher = { path = "../snitcher" }