hostname = "my-device"
homedir = "/var/lib/aziot/identityd"

[provisioning]
always_reprovision_on_startup = true
source = "manual"
iothub_hostname = "example.azure-devices.net"
device_id = "my-device"

[provisioning.authentication]
method = "x509"
identity_cert = "device-id"
identity_pk = "device-id"

[[principal]]
uid = 5558
name = "aziot-edge"
