[package]
name = "mqtt3-fuzz"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
license = "MIT"
edition = "2018"
publish = false

[dependencies]
afl = "0.6"
mqtt3 = { path = "../mqtt3" }
bytes = "1.0"
tokio-util = { version = "0.6", features = ["codec"] }

[build-dependencies]
bytes = "1.0"
mqtt3 = { path = "../mqtt3" }
tokio-util = { version = "0.6", features = ["codec"] }

[profile.dev]
codegen-units = 1 # Workaround for https://github.com/rust-fuzz/cargo-fuzz/issues/161

[profile.release]
codegen-units = 1 # Workaround for https://github.com/rust-fuzz/cargo-fuzz/issues/161
debug-assertions = true
