[package]
name = "hsm-sys"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
links = "iothsm"
build = "build.rs"
edition = "2018"

[dependencies]

[build-dependencies]
cmake = "0.1"

[dev-dependencies]
num_cpus = "1.0"
