[package]
name = "iotedged"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
edition = "2018"

[dependencies]
base64 = "0.9"
clap = "2.31"
chrono = "0.4"
env_logger = "0.5"
failure = "0.1"
futures = "0.1"
hyper = "0.12.17"
log = "0.4"
serde_json = "1.0"
serde = "1.0"
sha2 = "0.7.0"
tokio = "0.1.8"
tokio-signal = "0.2"
native-tls = "0.2"
url = "1.7"
url_serde = "0.2"

hsm = { path = "../hsm-rs"}
dps = { path = "../dps" }
docker = { path = "../docker-rs" }
edgelet-config = { path = "../edgelet-config" }
edgelet-core = { path = "../edgelet-core" }
edgelet-docker = { path = "../edgelet-docker" }
edgelet-hsm = { path = "../edgelet-hsm" }
edgelet-http = { path = "../edgelet-http" }
edgelet-http-hosting = { path = "../edgelet-http-hosting" }
edgelet-http-mgmt = { path = "../edgelet-http-mgmt" }
edgelet-http-workload = { path = "../edgelet-http-workload" }
edgelet-iothub = { path = "../edgelet-iothub" }
edgelet-utils = { path = "../edgelet-utils" }
iothubservice = { path = "../iothubservice" }
provisioning = { path = "../provisioning" }
signal-future = { path = "../signal-future" }

[target.'cfg(windows)'.dependencies]
windows-service = "0.1"
winapi = { version = "0.3.5", features = ["shellapi"] }

win-logger = { path = "../win-logger" }

[dev_dependencies]
tempdir = "0.3.7"

edgelet-test-utils = { path = "../edgelet-test-utils" }
