[package]
name = "iotedged"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false

[dependencies]
base64 = "0.9"
clap = "2.31"
config = "0.8"
env_logger = "0.5"
failure = "0.1"
futures = "0.1"
hyper = "0.11"
hyper-proxy = "0.4.1"
hyper-tls = "0.1"
log = "0.4"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
sha2 = "0.7.0"
tokio-core = "0.1"
tokio-signal = "0.1"
url = "1.7"
url_serde = "0.2"

hsm = { path = "../hsm-rs"}
docker = { path = "../docker-rs" }
edgelet-core = { path = "../edgelet-core" }
edgelet-docker = { path = "../edgelet-docker" }
edgelet-hsm = { path = "../edgelet-hsm" }
edgelet-http = { path = "../edgelet-http" }
edgelet-http-mgmt = { path = "../edgelet-http-mgmt" }
edgelet-http-workload = { path = "../edgelet-http-workload" }
edgelet-iothub = { path = "../edgelet-iothub" }
edgelet-utils = { path = "../edgelet-utils" }
iothubservice = { path = "../iothubservice" }
provisioning = { path = "../provisioning" }

[target.'cfg(windows)'.dependencies]
windows-service = "0.1"

win-logger = { path = "../win-logger" }

[dev_dependencies]
tempdir = "0.3.7"

edgelet-test-utils = { path = "../edgelet-test-utils" }

[target.'cfg(windows)'.build-dependencies]
winreg = "0.5.1"
version-compare = "0.0.6"
