[package]
name = "edgelet-test-utils"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
edition = "2018"

[dependencies]
async-trait = "0.1"
bytes = "1"
futures = "0.3"
futures-util = "0.3"
http = "0.2"
hyper = "0.14"
nix = "0.22"
openssl = "0.10"
serde = "1"

edgelet-core = { path = "../edgelet-core" }
edgelet-settings = { path = "../edgelet-settings" }

aziot-key-client = { git = "https://github.com/Azure/iot-identity-service", branch = "dps_certs" }
aziot-key-common = { git = "https://github.com/Azure/iot-identity-service", branch = "dps_certs" }
aziot-identity-common = { git = "https://github.com/Azure/iot-identity-service", branch = "dps_certs" }
