[package]
name = "edgelet-test-utils"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
edition = "2021"

[dependencies]
anyhow = "1"
async-trait = "0.1"
http = "0.2"
hyper = "0.14"
nix = "0.26"
serde = "1"
tokio = "1"

edgelet-core = { path = "../edgelet-core" }
edgelet-settings = { path = "../edgelet-settings" }

aziot-certd-config = { git = "https://github.com/Azure/iot-identity-service", branch = "main" }

cert-renewal = { git = "https://github.com/Azure/iot-identity-service", branch = "main" }
