[package]
name = "edgelet-test-utils"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
edition = "2018"

[dependencies]
chrono = "0.4"
failure = "0.1"
futures = "0.1"
hyper = "0.12"
objekt = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio = "0.1"

edgelet-core = { path = "../edgelet-core" }

[target.'cfg(unix)'.dependencies]
hyperlocal = "0.6"
