[package]
name = "edgelet-test-utils"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false

[dependencies]
chrono = "0.4"
failure = "0.1"
futures = "0.1"
hyper = "0.12"
hyperlocal = { git = "https://github.com/damonbarry/hyperlocal", branch = "windows" }
serde = "1"
serde_derive = "1"
serde_json = "1"
tokio = "0.1"

edgelet-core = { path = "../edgelet-core" }

[target.'cfg(windows)'.dependencies]
httparse = "1.2"
mio = "0.6"
mio-named-pipes = "0.1"
mio-uds-windows = { git = "https://github.com/damonbarry/mio-uds-windows.git" }
