[package]
name = "azure-iot-mqtt"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
license = "MIT"
edition = "2018"

[dependencies]
base64 = "0.11"
bytes = "0.5"
futures-core = "0.3"
futures-channel = "0.3"
futures-util = "0.3"
hmac = "0.7"
http = "0.2"
hyper = { version = "0.13", features = ["stream"] }
hyper-uds = { path = "../hyper-uds" }
lazy_static = "1.2"
log = "0.4"
native-tls = "0.2"
percent-encoding = "2"
regex = "1.1"
serde = { version = "1", features = ["derive", "rc"] }
serde_derive = "1"
serde_json = "1"
sha2 = "0.8"
tokio = { version = "0.2", features = ["tcp", "time", "process"] }
tokio-io-timeout = "0.4"
tokio-tls = "0.3"
tungstenite = "0.10"
url = "2"

mqtt3 = { git = "https://github.com/Azure/iotedge", rev = "4cd508" }

[dev-dependencies]
env_logger = "0.7"
structopt = "0.3"
tokio = { version = "0.2", features = ["signal", "stream"] }
