[package]
name = "azure-iot-mqtt"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
license = "MIT"
edition = "2018"

[dependencies]
base64 = "0.13"
bytes = "1"
futures-channel = "0.3"
futures-util = "0.3"
hmac = "0.12"
http = "0.2"
hyper = { version = "0.14", features = ["client", "http1", "stream", "tcp"] }
hyperlocal = "0.8"
lazy_static = "1"
log = "0.4"
native-tls = "0.2"
percent-encoding = "2"
regex = "1"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
sha2 = "0.10"
tokio = { version = "1", features = ["time", "process"] }
tokio-io-timeout = "1"
tokio-native-tls = "0.3"
tungstenite = "0.17"
url = "2"

mqtt3 = { path = "../../../../mqtt/mqtt3" }
