[package]
name = "iotedge-proxy"
description = "iotedge-proxy is a HTTPS proxy server to organize secure edge modules communication"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
edition = "2018"

[dependencies]
clap = "2.31"
config = { version = "0.9", default-features = false, features = ["yaml"] }
env_logger = "0.9"
failure = "0.1"
futures = "0.1"
hyper = "0.12"
hyper-tls = "0.3"
log = "0.4"
native-tls = "0.2"
openssl = "0.10"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
tokio = "0.1"
tokio-signal = "0.2"
url = "1.7"
url_serde = "0.2"

[dev-dependencies]
tempfile = "3"
