[package]
name = "snitcher"
version = "0.1.0"
authors = ["Azure IoT Edge Devs"]
publish = false
edition = "2018"

[dependencies]
azure_sdk_for_rust = "0.12"
backtrace = "0.3"
bytes = "0.4"
byteorder = "1.2"
chrono = { version = "0.4", features = ["serde"] }
# TODO: update these revisions to avoid security vulnerabilities
edgelet-http-mgmt = { git = "https://github.com/azure/iotedge", rev = "386bde07fb6af9fb55d44d38ad03fe31bb326011" }
edgelet-core = { git = "https://github.com/azure/iotedge", rev = "386bde07fb6af9fb55d44d38ad03fe31bb326011" }
env_logger = "0.5"
futures = "0.1"
hex = "0.3"
http = "0.1"
humantime = "1.1.1"
hyper = "0.12.36"
hyper-tls = "0.3.0"
libflate = "0.1"
log = "0.4"
openssl-probe = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_yaml = "0.8"
tar = "0.4"
tokio = "0.1"
url = "1.7"
url_serde = "0.2"

[target.'cfg(unix)'.dependencies]
tokio-uds = "0.2"

[target.'cfg(windows)'.dependencies]
tokio-uds-windows = { git = "https://github.com/Azure/tokio-uds-windows.git" }
