{{- if .Values.iotedged.data.persistentVolumeClaim }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.iotedged.data.persistentVolumeClaim.name | quote }}
  namespace: {{ include "edge-kubernetes.namespace" . | quote }}
  labels:
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: {{ include "edge-kubernetes.chart" . }}
spec:
  resources:
    requests:
      storage: {{ .Values.iotedged.data.persistentVolumeClaim.size }}
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.iotedged.data.persistentVolumeClaim.storageClassName | quote }}
  {{- end }}
